# -*- coding:utf-8 -*-

'''
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

'''
import time

def triangle(n):
    return (n+1)*n / 2


def get_factors(n):
    import math
    q = int(math.sqrt(n))
    a = [x for x in range(1, q + 1) if n % x == 0]
    a.extend([n/x for x in a if x != q])
    return a

start = time.time()
i = 1
a = get_factors(triangle(i))
while len(a) < 500:
    i += 1
    a = get_factors(triangle(i))

end = time.time()
print triangle(i)
print "time:", end - start, "s"
'''

import time

start = time.time()


def count_factors(n):
    result = 0
    for x in range(1, int(n**0.5) + 1):
        if n % x == 0:
            result += 2
            if x * x == n:
                result -= 1
    return result


def count_triangle_factors(limit):
    cnt = 0
    i = 1
    triangle = 0
    while cnt < limit:
        triangle = i * (i+1) / 2
        if i % 2 == 0:
            cnt = count_factors(i/2) * count_factors(i+1)
        else:
            cnt = count_factors(i) * count_factors((i+1)/2)
        i += 1
    return i-1, cnt, triangle


result = count_triangle_factors(500)
end = time.time()

print end - start, result

