# -*- coding:utf-8 -*-

'''
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

'''
import time

def triangle(n):
    return (n+1)*n / 2


def get_factors(n):
    import math
    q = int(math.sqrt(n))
    a = [x for x in range(1, q + 1) if n % x == 0]
    a.extend([n/x for x in a if x != q])
    return a

start = time.time()
i = 1
a = get_factors(triangle(i))
while len(a) < 500:
    i += 1
    a = get_factors(triangle(i))

end = time.time()
print triangle(i)
print "time:", end - start, "s"
'''

import time

prime_list = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


def divisor():
    time.clock()
    for x in xrange(10000, 55555):
        n_List = xrange(1, x)
        s = sum(n_List)
        fProduct = 1
        for i in xrange(0, len(prime_list)):
            counter = 1
            flag = True
            if prime_list[i] <= s:
                while flag:
                    d = s / prime_list[i]
                    m = s % prime_list[i]
                    if m != 0:
                        flag = False
                    else:
                        counter += 1
                        s = d
                fProduct *= counter
            else:
                break
        if fProduct > 500:
            return time.clock(), x, sum(n_List), fProduct


print divisor()
